server:
  port: 8083

spring:
  application:
    name: inventory-failover
  # port configuration to zipkin
  zipkin:
    enabled: false

# eureka client configuration
eureka:
  client:
    service-url:
      defaultZone: http://netflix:eureka@localhost:8761/eureka